import "dotenv/config";
import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const watch = process.argv.includes("--watch");

esbuild
  .context({
    banner: { js: banner },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    // Node / Electron built-ins: kept external so the AWS SDK credential
    // providers (fromNodeProviderChain, etc.) can use them via Electron's
    // native Node.js layer at runtime.  "node:*" matches the modern
    // `require("node:fs")` style used by the AWS SDK CJS bundles.
    external: [
      "obsidian",
      "electron",
      // Legacy built-in names
      "fs",
      "path",
      "os",
      "url",
      "crypto",
      "util",
      "child_process",
      "tls",
      "net",
      "http",
      "https",
      "http2",
      "vm",
      "zlib",
      "stream",
      "events",
      "buffer",
      "querystring",
      // Modern `node:` prefix variants (AWS SDK CJS bundles use these)
      "node:*",
    ],
    format: "cjs",
    // Force the Node.js (CJS) builds of credential-related packages so they
    // use NodeHttpHandler (Node TLS) rather than FetchHttpHandler (browser
    // fetch). Without these aliases, esbuild's default browser-mode resolution
    // picks the ESM bundle for @aws-sdk/nested-clients/sso, which ships
    // FetchHttpHandler and causes "TypeError: Failed to fetch" when the SSO
    // credential provider tries to call sso.amazonaws.com from inside
    // Obsidian's Electron renderer (where cross-origin fetch is restricted).
    alias: {
      "@aws-sdk/credential-providers":
        "./node_modules/@aws-sdk/credential-providers/dist-cjs/index.js",
      "@aws-sdk/credential-provider-sso":
        "./node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js",
      "@aws-sdk/nested-clients/sso":
        "./node_modules/@aws-sdk/nested-clients/dist-cjs/submodules/sso/index.js",
      "@aws-sdk/token-providers":
        "./node_modules/@aws-sdk/token-providers/dist-cjs/index.js",
    },
    // es2020 required for BigInt literals used by @aws-sdk/crc64-nvme
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outfile: "main.js",
    define: {
      global: "window",
      "process.env.NODE_DEBUG": "undefined",
      "process.env.DEBUG": "undefined",
      // Prevents azure-sdk compat checks from breaking the bundle
      "globalThis.process.versions": "undefined",
    },
  })
  .then((ctx) => {
    if (watch) {
      ctx.watch();
    } else {
      ctx.rebuild().then(() => ctx.dispose());
    }
  })
  .catch(() => process.exit(1));
